// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tWx0YaIAzAYrscoBdpLD2is1WrY4HR4',
    appId: '1:734434623638:android:618d2e93bdf2e8d9ba42b7',
    messagingSenderId: '734434623638',
    projectId: 'weather-963bf',
    storageBucket: 'weather-963bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxyYEl3fIboWU4e6U9uUAZt3W4ulHSbzw',
    appId: '1:734434623638:ios:b29a1057e10efbecba42b7',
    messagingSenderId: '734434623638',
    projectId: 'weather-963bf',
    storageBucket: 'weather-963bf.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidGSgE62wPHvc3cJAsXUye8ka6xv8zzg',
    appId: '1:734434623638:web:6a13c64ac70dcb07ba42b7',
    messagingSenderId: '734434623638',
    projectId: 'weather-963bf',
    authDomain: 'weather-963bf.firebaseapp.com',
    storageBucket: 'weather-963bf.firebasestorage.app',
    measurementId: 'G-88CBHBBN5S',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDidGSgE62wPHvc3cJAsXUye8ka6xv8zzg',
    appId: '1:734434623638:web:d04dd261f1e67d22ba42b7',
    messagingSenderId: '734434623638',
    projectId: 'weather-963bf',
    authDomain: 'weather-963bf.firebaseapp.com',
    storageBucket: 'weather-963bf.firebasestorage.app',
    measurementId: 'G-J77BZRWWQQ',
  );

}